import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  console.log('[2025-10-12T' + new Date().toISOString() + '] generate-infographic-bg function invoked');

  try {
    // Parse request body for custom prompt
    const { prompt } = await req.json().catch(() => ({}));
    
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Use custom prompt or default background prompt
    const backgroundPrompt = prompt || `Create a professional abstract background image (1080x1350px) for a corporate infographic.

CRITICAL RULES - MUST FOLLOW:
- NO TEXT, NO LETTERS, NO NUMBERS, NO LOGOS whatsoever
- Only abstract shapes, gradients, and corporate design elements
- This is ONLY a background plate for text overlay

COLOR PALETTE (IDVL Corporate Identity):
- Primary gradient: #232d42 (top) to #1e6efb (bottom)
- Accent shades: use variations of blue (#1e6efb, #2563eb, #3b82f6)
- Professional corporate aesthetic

LAYOUT REQUIREMENTS:
- Top section (0-150px): clean area for header text and logo
  - Keep top-left corner (200x60px) completely clean for logo placement
- Middle section (150-1230px): subtle abstract elements, good contrast for white/light cards
  - Can have gentle diagonal lines, dots, or abstract shapes
  - Maintain readability for overlaid text
- Bottom section (1230-1350px): clean area for footer
  - Keep bottom-right corner (100x30px) completely clean for logo placement

STYLE:
- Modern, minimalist, corporate
- Subtle textures or geometric patterns allowed
- High contrast to ensure text readability
- Professional gradient transitions
- Clean, elegant, suitable for social media

REMEMBER: This is ONLY a background. No text, no data, no logos. Just a beautiful corporate blue gradient background with subtle abstract elements.`;

    console.log('Generating background with AI (1080x1350px, no text/logos)');
    const startTime = Date.now();

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: backgroundPrompt
          }
        ],
        modalities: ['image', 'text']
      }),
    });

    if (aiResponse.status === 429) {
      console.error('❌ Rate limit exceeded');
      return new Response(
        JSON.stringify({ error: 'Rate limit exceeded. Please try again later.' }),
        { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (aiResponse.status === 402) {
      console.error('❌ Payment required');
      return new Response(
        JSON.stringify({ error: 'Payment required. Please add credits to your workspace.' }),
        { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('❌ AI API error:', aiResponse.status, errorText);
      throw new Error(`AI API error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    const imageUrl = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!imageUrl) {
      console.error('❌ No image in AI response');
      throw new Error('No image generated by AI');
    }

    const elapsed = Date.now() - startTime;
    console.log(`✅ Background generated successfully in ${elapsed}ms`);

    return new Response(
      JSON.stringify({ imageUrl }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );

  } catch (error) {
    console.error('❌ Error in generate-infographic-bg:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Failed to generate background' 
      }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  }
});
