// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veuuwtxfrrmztrjchptn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldXV3dHhmcnJtenRyamNocHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDkxMjUsImV4cCI6MjA2MTc4NTEyNX0._iH2SnGz_QNnk1p5g9eq_ROhmtZ6Hhe8KzqvwbVgNU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);